### PR TITLE
Enhancement: Custom CSPROJ

### PR DESCRIPTION
**Pull request by AndrewDRX**
Pull request for issue #10.

Feel free to just use this pull request as inspiration for another commit if you want it structured a bit different than I have it.

### CODE REVIEW

**Comment by SomeRanDev** [comment]
Sorry for the delay! Was waiting on @jeremyfa's printer rework before accepting, but will do now since that might take a bit longer. 

For future reference, I think we should only use underscores for define names since dashes break compatibility with conditional compilation. (ie: `#if no-csproj` doesn't work afaik?) Even if we don't use a define like this, some Reflaxe/C# users might? I know official Haxe defines are inconsistent, but no reason we should be? 😅

**Comment by AndrewDRX** [comment]
> Sorry for the delay! Was waiting on @jeremyfa's printer rework before accepting, but will do now since that might take a bit longer.
> 
> For future reference, I think we should only use underscores for define names since dashes break compatibility with conditional compilation. (ie: `#if no-csproj` doesn't work afaik?) Even if we don't use a define like this, some Reflaxe/C# users might? I know official Haxe defines are inconsistent, but no reason we should be? 😅

Sounds good! Although, the `csproj` define is the only new one here. The `no-csproj` define already existed, I just added more structure around it by adding it to the `Define` enum so there would be consistency when checking for both of them in ```setupCsProj()```. But I will keep that on my radar to switch it to ```no_csproj``` at some point if no one else gets to it before me.

**Comment by jeremyfa** [comment]
Could have been me who added that option I don't remember, but I completely agree with using underscores instead of dashes 👍

**Comment by SomeRanDev** [comment]
OH SORRY! In retrospect, I'm almost 100% sure I added that, and I forgot about it until seeing this. I just wanted to give an explanation so it didn't seem like I was changing things randomly after merging. 😅

**Pull request merged**
